### ISSUE TITLE
ConnectionResetError when client disconnects abruptly

### ISSUE THREAD

**Issue by sanjioh** [aio-libs/aiosmtpd#127]
Hi,

when a client disconnects abruptly, `aiosmtpd` logs an unhandled `ConnectionResetError`, that follows an attempt to return a status code to the client once it has already gone.

I managed to reproduce the issue quite consistently with the following handler and CLI command:

```python
import asyncio
from concurrent.futures import CancelledError, ProcessPoolExecutor


def func():
    pass


class Handler:
    def __init__(self):
        self._executor = ProcessPoolExecutor(4)

    async def handle_DATA(self, server, session, envelope):
        loop = asyncio.get_event_loop()
        try:
            await loop.run_in_executor(self._executor, func)
        except CancelledError:
            print('cancelled')
        return '250 OK'
```

CLI: `python -m aiosmtpd -n -c handler.Handler`

I used a benchmarking tool (https://github.com/nabeken/go-smtp-source) as client, which sends a user defined number of messages of a certain size, concurrently.
If I stop the test hitting CTRL-C on the client, I get the following output from aiosmtpd (sometimes it takes a couple of retries to reproduce, but it should be quite easy):

```
cancelled
ERROR:mail.log:SMTP session exception
Traceback (most recent call last):
  File "/home/fabio/.virtualenvs/mailsampler/lib/python3.6/site-packages/aiosmtpd/smtp.py", line 281, in _handle_client
    await method(arg)
  File "/home/fabio/.virtualenvs/mailsampler/lib/python3.6/site-packages/aiosmtpd/smtp.py", line 677, in smtp_DATA
    await self.push('250 OK' if status is MISSING else status)
  File "/home/fabio/.virtualenvs/mailsampler/lib/python3.6/site-packages/aiosmtpd/smtp.py", line 203, in push
    await self._writer.drain()
  File "/opt/pyenv/versions/3.6.2/lib/python3.6/asyncio/streams.py", line 323, in drain
    raise exc
  File "/opt/pyenv/versions/3.6.2/lib/python3.6/asyncio/selector_events.py", line 724, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer
ERROR:mail.log:Exception in handle_exception()
Traceback (most recent call last):
  File "/home/fabio/.virtualenvs/mailsampler/lib/python3.6/site-packages/aiosmtpd/smtp.py", line 292, in _handle_client
    await self.push(status)
  File "/home/fabio/.virtualenvs/mailsampler/lib/python3.6/site-packages/aiosmtpd/smtp.py", line 203, in push
    await self._writer.drain()
  File "/opt/pyenv/versions/3.6.2/lib/python3.6/asyncio/streams.py", line 323, in drain
    raise exc
  File "/home/fabio/.virtualenvs/mailsampler/lib/python3.6/site-packages/aiosmtpd/smtp.py", line 281, in _handle_client
    await method(arg)
  File "/home/fabio/.virtualenvs/mailsampler/lib/python3.6/site-packages/aiosmtpd/smtp.py", line 677, in smtp_DATA
    await self.push('250 OK' if status is MISSING else status)
  File "/home/fabio/.virtualenvs/mailsampler/lib/python3.6/site-packages/aiosmtpd/smtp.py", line 203, in push
    await self._writer.drain()
  File "/opt/pyenv/versions/3.6.2/lib/python3.6/asyncio/streams.py", line 323, in drain
    raise exc
  File "/opt/pyenv/versions/3.6.2/lib/python3.6/asyncio/selector_events.py", line 724, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer
```

Am I missing something? Can this be confirmed?

Thank you very much for your work on aiosmtpd!

**Comment by sanjioh** [comment]
Hi @warsaw, can you please provide any feedback on this? I by no means intend to rush you, I'm just interested in knowing if I can do anything in my code to prevent this issue. Thanks!

**Comment by sanjioh** [comment]
sorry, ping?

**Comment by sanjioh** [comment]
Hi,

I came back onto this after some time.

I have some news: I could NOT reproduce the reported behavior on Python 3.8.0, but it's still present in Python 3.7.5.
I assume some recent changes to asyncio have somehow fixed it. After digging into the changelog and into the code, I'm still not able to tell what actually made the difference.

It would be nice if something could be done to have aiosmtpd behave the same way on Python <3.8 as well; I'm not sure if this is actually possible though.

**Comment by waynew** [comment]
Thanks for the update! That's...  interesting. I wonder if there's a bug that was filed on the Python issue tracker?

It might be possible to just throw a  try/catch around that line, handling the `ConnectionResetError`. I'd check the code from upstream Python to see how it's changed to see if we can just do something similar to that...

**Comment by sanjioh** [comment]
Thank you, much appreciated. Please let me know if you need further information or hints about how to reproduce the problematic behavior.

**Comment by wevsty** [comment]
I've spent some time researching the problem I'm having and the issues @sanjioh is having.

I figured out why @sanjioh doesn't have this problem after upgrading to Python 3.8.
The reason is that before 3.8 CancelledError was an Exception, after 3.8 CancelledError is changed to BaseExceptions.
This change is available at  https://bugs.python.org/issue32528

Why this change will fix the problem?

```python
            except asyncio.CancelledError:
                # The connection got reset during the DATA command.
                # XXX If handler method raises ConnectionResetError, we should
                # verify that it was actually self._reader that was reset.
                log.info('Connection lost during _handle_client()')
                self._writer.close()
                raise
            except Exception as error:
                try:
                    status = await self.handle_exception(error)
                    await self.push(status)
                except Exception as error:
                    try:
                        log.exception('Exception in handle_exception()')
                        status = '500 Error: ({}) {}'.format(
                            error.__class__.__name__, str(error))
                    except Exception:
                        status = '500 Error: Cannot describe error'
                    await self.push(status)
```
We can see the code.
CancelledError exception is thrown after write.close() is called.
In versions prior to Python 3.8, re-thrown exceptions would be caught again and processed, but since the connection was closed self.push() would show a ConnectionResetError error, So finally tried twice and will saw the error message twice.
After Python 3.8, the CancelledError thrown again will not be caught by the except Exception, so you won't see a similar prompt.

And the ConnectionResetError I encountered was caused by the client actively disconnecting and still calling self.push(), which is a separate issue that I will submit a PR to fix.
