### ISSUE TITLE
500 Error (NameError) name 'error_occurred' is not defined

### ISSUE THREAD

**Issue by nicknomo** [aio-libs/aiosmtpd#129]
Using telnet I send a EHLO, I sent a MAIL FROM and RCPT TO... I then send DATA and enter a data line... but as soon as I hit enter it throws this error inside of telnet:

500 Error (NameError) name 'error_occurred' is not defined

The python console shows the following:

SMTP session exception
Traceback (most recent call last):
  File "C:\Program Files\Python3.6\python-3.6.1.amd64\aiosmtpd\smtp.py", line 281, in _handle_client
    await method(arg)
  File "C:\Program Files\Python3.6\python-3.6.1.amd64\aiosmtpd\smtp.py", line 657, in smtp_DATA
    status = await self._call_handler_hook('DATA')
  File "C:\Program Files\Python3.6\python-3.6.1.amd64\aiosmtpd\smtp.py", line 118, in _call_handler_hook
    status = await hook(self, self.session, self.envelope, *args)
  File "smtprelay.py", line 13, in handle_DATA
    if error_occurred:
NameError: name 'error_occurred' is not defined

The code that is currently being run was pulled straight from the documenation:
http://aiosmtpd.readthedocs.io/en/latest/aiosmtpd/docs/migrating.html

Any idea what is going on here?

**Comment by Mortal** [comment]
"error_occurred" is a meta-variable -- you're supposed to change that to checking for whatever error condition was handled in your smtpd application. If you don't anticipate any errors, remove the "if error_occurred:" statement.

**Comment by nicknomo** [comment]
Wow, do not program when sleep deprived kids...  I saw the trace, but my brain didn't seem to want to work.  I kept looking in smtp.py looking for where error_occurred was used.  I never even saw the "File "smtprelay.py", line 13, in handle_DATA" .  It also didn't help that I didn't read the sample code, and I just assumed it was working code.  

Thanks for the reply, and sorry to waste your time...
