### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by denself** [aio-libs/aiosmtpd#130]
Attempt to send message with non-ascii symbols results in `UnicodeEncodeError`:
```python
>>> from smtplib import SMTP as Client
>>> client = Client('127.0.0.1', 8025)
>>> r = client.sendmail('a@example.com', ['b@example.com'], "Ї")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python3.6/smtplib.py", line 854, in sendmail
    msg = _fix_eols(msg).encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\u0407' in position 0: ordinal not in range(128)
```
Is there any particular reason to use `.encode('ascii')` instead of just `.encode()`?

**Comment by Mortal** [comment]
That's an issue with `smtplib` in the Python standard library and not an issue with aiosmtpd. You can just encode the string as UTF-8 before passing to `sendmail()`, that is:

```
r = client.sendmail('a@example.com', ['b@example.com'], "Ї".encode('utf-8'))
```

Or even better, create an [EmailMessage](https://docs.python.org/3/library/email.message.html#email.message.EmailMessage) or [Message](https://docs.python.org/3/library/email.compat32-message.html#email.message.Message) instance representing your email and using `as_bytes()` to serialize it using valid encoding. But again, this is part of the standard library and not aiosmtpd.

**Comment by denself** [comment]
@Mortal Thank you for your fast reply, my mistake, misunderstood traceback. Closing this.
