### ISSUE TITLE
Allow customization of __ident__ field in SMTP class

### ISSUE THREAD

**Issue by kz26** [aio-libs/aiosmtpd#131]
It would be useful to refactor __ident__ into a customizable field on the SMTP class, e.g. if you want to hide the fact that the server is Python-powered.

**Comment by Mortal** [comment]
Indeed, this is currently not well supported.

I think the right approach would be to introduce a hook for when the connection has been established.

As a workaround, you can import aiosmtpd.smtp and write to `aiosmtpd.smtp.__ident__` directly.
