### ISSUE TITLE
How to bind all interfaces dual-stack?

### ISSUE THREAD

**Issue by jaraco** [aio-libs/aiosmtpd#140]
I wish to write a server application that binds to all interfaces in a dual-stack IPv4/IPv6 environment.

I thought the example server would be doing that, as it appears to bind to '::0'. In other applications, like CherryPy, binding to that address makes the server available on all interfaces, IPv4 and IPv6, but in aiosmtpd, the server is only reachable on IPv6. As a result, when the application moves to an environment that only supports IPv4 (looking at you, Docker), the application is unreachable.

Reading up on the [docs for create_server](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.AbstractEventLoop.create_server), I see that passing a `None` value for the host should bind to all interfaces on both stacks, and indeed, that's the behavior I see.

But aiosmtpd doesn't allow passing `None` due to the the [localhost default behavior](https://github.com/aio-libs/aiosmtpd/blob/23b743be942ffd37f9c051c1f6efe0108ffd456d/aiosmtpd/controller.py#L14).

I did find one interface that worked, but I'm not happy with it:

```
	cont = controller.Controller(proxy, port=8025)
	# no really, I want all interfaces
	cont.hostname = None
	cont.start()
```

**Comment by jaraco** [comment]
One approach I'm considering is to use a value other than `None` as the sentinel for "hostname unspecified", have that value be translated into `::1`.

But as I consider that, I realize the issue is broader. What if one specifies "::1" or relies on the default fallback - that binding also will be IPv6 only.

I'd really like to be able to bind to all interfaces in a dual-stack way.

**Comment by jaraco** [comment]
I do see that one may pass `['::1', '127.0.0.1']` for hostname, and that does bind to both stacks. Similarly, `['::0', '0.0.0.0']` works.

**Comment by jaraco** [comment]
Also, binding to `'localhost'` will bind similarly to `['::1', '127.0.0.1']`, but as far as I know, there's no way to simply specify "all interfaces".

Another solution I'm considering is for aiosmtpd to present a constant:

```
all_interfaces = ['::0', '0.0.0.0']
"hostname to bind to all interfaces"
```

And use that in the example server to draw attention to it.

**Comment by jaraco** [comment]
Aha! I just noticed that `create_server` also accepts `''` to indicate all interfaces. And that does work in aiosmtpd. I think for now I'll update the docstring to reflect that as a recommendation.

**Comment by jaraco** [comment]
I've presented a PR, and that approach feels minimally invasive to address the concern.

**Comment by Mortal** [comment]
I think we can label this issue "rubber ducking" :-)

Thanks for the PR and for figuring this out!
