### ISSUE TITLE
EHLO command returns all bunch of 250- data, even when the hooks returns otherwise

### ISSUE THREAD

**Issue by cnicodeme** [aio-libs/aiosmtpd#155]
[In the current state of the code](https://github.com/aio-libs/aiosmtpd/blob/master/aiosmtpd/smtp.py#L351), some data are pushed BEFORE calling the hook, including

```
    250-{hostname}
    250-SIZE ...
    250-8BITMIME
    250-SMTPUTF8
    250-STARTTLS
```

And AFTER that, the hook is called.

The issue is that if the hook doesn't return a 2xx response, the server sends a mixed response and makes the clients fails.

The `EHLO` command should call the hook, and depending on the response, send all the push commands afterward.

**Comment by waynew** [comment]
Just trying to understand here - is there a case where you would want to return a different response to the EHLO and still succeed?

I know personally I haven't had a need for that, but I'm not sure what the valid use cases are.

**Comment by waynew** [comment]
I just did some searching and I haven't been able to find a really great reason that EHLO should be returning anything besides a 250.

The only reason I can think of that you might be returning something different is that you've got some kind of broken setup - which indicates that you need to fix your code, not that there's an issue here.

But if there's some case that I have considered, I'd love to hear about it!

**Comment by cnicodeme** [comment]
Hi @waynew ! I do have an example :)

When the server connects to the SMTP daemon, the `HELO`/`EHLO` command can allow many checks that can lead to refusal:

1. checking if the IP has a PTR record
2. checking that the hostname matches the PTR of that the SPF records allow the IP to send emails
3. Checking that the sending IP is not on a blacklist (Spamhaus for instance)

If one of those checks fails, you can return a 4xx/5xx to refuse the connection, before going further.

But with the `EHLO` command, aiosmtpd has already returned `250-*` messages before sending that 4xx/5xx code, so it's not good.

Hope that makes sense :)

**Comment by waynew** [comment]
Hey @cnicodeme yeah, thanks! That definitely makes sense. Do you have any ideas about how we would want to change this? Pull requests of course are always welcome :)

**Comment by cnicodeme** [comment]
I've sent a PR (#157). Let me know what you think.

The PR also kind of join the idea of having `None` returned for the hooks instead of `MISSING`. (see #154 )

**Comment by agronholm** [comment]
If there is no way to override the 250 response, how can I test that my SMTP client can fall back to `HELO`when `EHLO` fails?

**Comment by agronholm** [comment]
Answering my own question, overriding `smtp_EHLO()` is the only way.
