### ISSUE TITLE
Drop Python 3.4 support

### ISSUE THREAD

**Issue by warsaw** [aio-libs/aiosmtpd#16]
We should probably drop Python 3.4 support.  For one thing, I don't have a good way to run the 3.4 tests locally.  We could of course just rely on CI to verify that continues to work.

More importantly though, I think it would be really nice to be able to use the new Python 3.5 async keywords.

**Comment by sirkonst** [comment]
You can use [pyenv](https://github.com/yyuu/pyenv) (and maybe with docker) for setup test enviroment for python 3.4.

Drop support 3.4 is not a good idea, now at least.

**Comment by warsaw** [comment]
I'd have to build 3.4 from source to test it on my main development desktops, which I really don't want to do.  But for now, now that CI is working again, I'd be fine with just letting Travis verify that all supported versions of Python pass the test suite.

I don't think we need to milestone this bug any time soon, but 3.4 is in source-only security fix mode, and once 3.6 gets released, 3.4 will likely EOL.  So it should be on our radar to stop official 3.4 support (and add support for 3.6).

**Comment by kozzztik** [comment]
Agree. There are much things that Python 3.4 doesn`t support. Most important for me is async/await, I love when code is beautiful itself and yield froms with decorators are dirty. Also Python 3.4 not supports SSL in proper way.
But also, workarouds for all of that already in, and removing support may significally decrease auditory.

**Comment by warsaw** [comment]
Just dropping this here because it looks pretty cool and could help with documenting functions once we switch to `async def` style.  https://sphinxcontrib-trio.readthedocs.io/en/latest/

**Comment by warsaw** [comment]
I'd like to merge this soon.  Question for @kozzztik and @Mortal - do you think we need to bump the major version number to 2.0 or can we drop Python 3.4 support in 1.1.  For me, it doesn't change the plans for the next version, just what to call it (e.g. aiosmtpd 1.1 or 2.0).

Personally, I'm fine with calling it 1.1 even after dropping Python 3.4 support, so the PR will be updated with that in mind.  If you have strong opinions otherwise, I'll just rename the 1.1 milestone to 2.0.

**Comment by Mortal** [comment]
I think calling it 1.1 is fine. Hopefully most aiosmtpd users will be on at least Python 3.5 by now :-)
