### ISSUE TITLE
Controller.start uses threading

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/aiosmtpd#160]
https://github.com/aio-libs/aiosmtpd/blob/3ced778177418d8ae47bc3c300879bf59e731f1a/aiosmtpd/controller.py#L54

It seems to be that `Controller.start` using `Threading` is not required and will lead to problems.

Like the asyncio http server starting an SMTP server should not involve threading, but just `loop.run_forever()`.

**Comment by waynew** [comment]
@samuelcolvin thanks for the report! Do you have some docs or examples that we could reference?

**Comment by samuelcolvin** [comment]
Take a look at aiohttp's [run_app](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web.py#L375) or its documentation on [Runnings Applications](https://docs.aiohttp.org/en/stable/web_reference.html#running-applications).

**Comment by pepoluan** [comment]
@samuelcolvin so if I don't misunderstood, you want to split out the thread-starting ability from Controller?

**Comment by nhoad** [comment]
Why is the default behavior to run in a thread?

Mirroring Samuel's request, having the ability to run it in the foreground without any threading would be useful.

**Comment by pepoluan** [comment]
@nhoad One thing to realize is that `Controller` is just a "convenience class" to instantiate the SMTP server.

The code for `Controller` is very well designed; if you need a non-threading, in-the-foreground solution, you can simply take the code within the `Controller._run()` method (that is, select the text, copy them, and paste in your code) and run it.

All the intelligence of the SMTP server happens in the `aiosmtpd.smtp.SMTP` class; it's self-contained.

**Comment by pepoluan** [comment]
I have a branch waiting for #247 to be merged first.

**Comment by pepoluan** [comment]
Boy oh boy... apparently implementing unthreaded controllers is much more complex than I thought.

Testing them properly is a whole 'nother level.

**Comment by pepoluan** [comment]
If anyone wants to take a peek and/or kick the tires, be my guest: https://github.com/pepoluan/aiosmtpd/tree/unthreaded-controller

**Comment by pepoluan** [comment]
The branch is about 95% complete, documentation also updated.

Feel free to check it out @samuelcolvin @nhoad
