### ISSUE TITLE
Task was destroyed but it is pending

### ISSUE THREAD

**Issue by cnicodeme** [aio-libs/aiosmtpd#163]
Hi,

checking at my errors when running aiosmtpd in production, I get a lot of "Task was destroyed but it is pending!" errors, with this detail following:

> task: <Task pending coro=<AioSMTP._handle_client() running at /var/www/towboat/server/workers/utils/aiosmtp.py:344> wait_for=<Future pending cb=[Task._wakeup()]>>

I tried to locate the reason why/when this happens, but so far, no luck.

I'm hoping I'm not the only one here, and maybe someone has a solution?

**Comment by waynew** [comment]
Hi @cnicodeme thanks for the report!

Are you using aiosmtpd as-is, or have you built something on top of it?

**Comment by cnicodeme** [comment]
I do changed a bit on some parts. I pushed the code on Gist here: https://gist.github.com/cnicodeme/5da6eea98f15325f4456dedaef09d432

Concretely, I use a TlsController to handle TLS connections (which I call on the `main.py` code).

I've also changed a few parts of the `smtp.py` code from here. Mostly, here are the changes I did:

 * Limiting the number of the same request, to avoid a client sending 100 `RCPT TO` for instance.
 * Timeout between each command (if no commands in a specific amount of time, the connection is closed). This is to avoid long opened connections
 * Global timeout. This is to ensure that someone doesn't play with the time by calling various commands (`RSET`, `HELP`, etc)
 * _call_handler_hook returns `None`, not `MISSING`, and all the parts on the code has been adapted to this response. I thought that it made more sense to do the default action when `None` was returned, which allowed me to return `None` also from a handler in some case.

You can do a diff from the master file to highlight the changes I listed. Other than that, there is nothing too fancy.

For information, the error occurs on the readline call from the reader stream on the _handle_client function. (here : https://gist.github.com/cnicodeme/5da6eea98f15325f4456dedaef09d432#file-aiosmtpd-py-L344 )

Let me know if you need any details.

**Comment by pepoluan** [comment]
Hi @cnicodeme , since this Issue is quite old ( > 1 year since last update), are you still having the same issue, or can we close this?

Just FYI the latest `master` had some optimizations introduced to make `_handle_client()` perform faster; you might want to test your code against the latest commit.

**Comment by cnicodeme** [comment]
Yeah, I need to update my code to your latest updates and see how it goes. I have made a tons of change from your original one so I'll need to ensure everything works fine, but we can close this ticket for now, and if this continues to happen with the update, I'll re-open a new ticket.
