### ISSUE TITLE
Using this as the base for a personal email server

### ISSUE THREAD

**Issue by Technerder** [aio-libs/aiosmtpd#165]
Would it be plausible to use this library to build a personal email server?

**Comment by waynew** [comment]
@Technerder Yes it is! I actually started a project, [orouboros](https://github.com/waynew/orouboros) that does exactly that. It's *very* beta right now, but, it works!

**Comment by Mortal** [comment]
See also: [Python aiosmtpd - what is missing for an Mail-Transfer-Agent (MTA)?](https://stackoverflow.com/questions/45734960/python-aiosmtpd-what-is-missing-for-an-mail-transfer-agent-mta) where I wrote two of the answers, discussing some things to consider before using aiosmtpd as the SMTP server facing the public internet. In short, I would strongly suggest using Postfix as the public-facing server, with aiosmtpd behind to handle any business logic you want to implement.
