### ISSUE TITLE
Feature request: autoreload

### ISSUE THREAD

**Issue by louisabraham** [aio-libs/aiosmtpd#166]
Hi, it would be great to support auto-reloading like gunicorn.

**Comment by asvetlov** [comment]
Please elaborate what exactly should be done on auto-reloading and what event should trigger this action.
Even better: please provide a pull request!

**Comment by louisabraham** [comment]
Changing the code should trigger a reload of the server.

See <http://docs.gunicorn.org/en/stable/settings.html#reload>. They use 2 different ways to monitor files: inotify and polling.

**Comment by asvetlov** [comment]
Do you think program killing at random point is a good thing?
Like dropping open sockets, kicking connecting users, write only partial data to database/filesystem/whatever?

Also please keep in mind: `aiosmtpd` is a *library* to build smtp server, not a server *program* itself.

**Comment by louisabraham** [comment]
> Do you think program killing at random point is a good thing?

no

> Like dropping open sockets, kicking connecting users, write only partial data to database/filesystem/whatever?

I wasn't suggesting that. The restart could occur only when not processing a message, with a daemon that keeps queuing incoming packets to be treated.

There is still a basic CLI tool to run a server. Do you have alternative servers to recommend?

**Comment by pepoluan** [comment]
> There is still a basic CLI tool to run a server. Do you have alternative servers to recommend?

The key word I believe is "basic".

If you need more functionality, you can build a more full-featured server above the `aiosmtpd` library.

As such, I think we should close this Issue, at least for the time being. Should anyone think we need to do such development, feel free to reopen.
