### ISSUE TITLE
Test failures and DeprecationWarnings in Python 3.8

### ISSUE THREAD

**Issue by tirkarthi** [aio-libs/aiosmtpd#167]
There are test case failures in Python 3.8 . I think this is due to mocking `create_server` which is now `AsyncMock` instead of `MagicMock` with changes in https://bugs.python.org/issue26467 where coroutines when patched return `AsyncMock`. Thus there are warnings due to the mock not being awaited. The old behavior can be used with `MagicMock` explicitly passed while patching. There also seems to be a bug that `AsyncMock` is not recording `call_args` and other values for synchronous API.

There is also DeprecationWarning since `StreamReader` and `StreamWriter` are merged into `Stream` class in https://bugs.python.org/issue36889. Attached is a log with 3.9.0a0 but these are reproducible on 3.8.0b1 as well.

[aiosmptd.log](https://github.com/aio-libs/aiosmtpd/files/3318345/aiosmptd.log)

**Comment by waynew** [comment]
There's also `PendingDeprecationWarning: Task.all_tasks() is deprecated, use asyncio.all_tasks() instead`

**Comment by pepoluan** [comment]
This will be irrelevant when #192 is merged because that PR took out the whole suite of test cases that caused these warnings.
