### ISSUE TITLE
1.2.1 is not available on PyPI

### ISSUE THREAD

**Issue by ddevault** [aio-libs/aiosmtpd#168]

**Comment by ddevault** [comment]
bump

**Comment by dvzrv** [comment]
Hi! I'm packaging python-aiosmtpd for Arch Linux. We usually track pypi's upstream for changes and use the sdist tarballs from there, because they have unique naming.

Please keep the tagged versions in this repository and the releases on pypi in sync. Thanks!

**Comment by edeca** [comment]
+1, please could version 1.2.1 be uploaded to PyPI?

**Comment by waynew** [comment]
Well, clearly this has taken a bit too long. I *believe* that 1.2.1 actually has been uploaded already, as 1.2.

That being said, the version reported will be `1.2+` -- that's what in GitHub right now with the tag 1.2.1

If that's good enough we can leave it as-is, or alternatively we can cut a 1.2.2 release that only exists to bump the `__version__` number in `smtp.py`.

**Comment by dvzrv** [comment]
@waynew A bump would of course be much appreciated. Thanks!

**Comment by pepoluan** [comment]
+1 for a bump to 1.2.2 @waynew

**Comment by dvzrv** [comment]
@waynew  Thanks for releasing 1.2.2. This can be closed!
