### ISSUE TITLE
Add license to repository

### ISSUE THREAD

**Issue by jayvdb** [aio-libs/aiosmtpd#170]
Please add a license file to the repository, and include it in any distributions of the source code.

**Comment by pepoluan** [comment]
@waynew @warsaw @asvetlov are we ready to choose a license?

I _personally_ love MPL 2.0, but I'll defer to you guys.

**Comment by warsaw** [comment]
The Python Software Foundation has two acceptable incoming licenses in their [Contributor Agreement](https://legacy.python.org/psf/contrib/contrib-form/contributor-agreement.pdf).  Of the two, I prefer Apache 2.0 so that's why I chose it for `atpublic` and all my other public Python projects.

**Comment by asvetlov** [comment]
+1 for Apache 2
PSF license is Apache 2 based AFAIK

**Comment by pepoluan** [comment]
Hooooldup ... this issue is kinda moot actually.

[**We already specified the License used**](https://github.com/aio-libs/aiosmtpd#license)

We only forgot to put in the `LICENSE` file. #197 fixes this oversight.
