### ISSUE TITLE
SSLError "no shared cipher"

### ISSUE THREAD

**Issue by cnicodeme** [aio-libs/aiosmtpd#173]
Hi!

I noticed that some clients, when connecting to SMTP with STARTTLS, don't have a cipher that matches the one enabled on my end. This causes a SSLError with the message "No shared cipher"

```
SSLError: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1056)
  File "asyncio/sslproto.py", line 625, in _on_handshake_complete
    raise handshake_exc
  File "asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
```

This exception is logged via asyncio and is caused in the SSL wrapper.
I'm wondering if there is a way to catch this issue?

**Comment by waynew** [comment]
Hi @cnicodeme thanks for the report!

That's unfortunate, for sure. I'm not sure if we have a mechanism for this yet, but we definitely should. Would you be interested and able to look into this?
