### ISSUE TITLE
Controller does not allow opportunistic TLS

### ISSUE THREAD

**Issue by agronholm** [aio-libs/aiosmtpd#179]
When a TLS context is passed to the controller and it is started, it starts a server which **implicitly** does the TLS handshake for all new clients. This behavior is not mentioned in the documentation. Not only that, but there seems to be no way to properly use `STARTTLS` without overriding the constructor and the `factory()` method of the `Controller` class to pass the context to the protocol, bypassing the server setup.

**Comment by waynew** [comment]
Hi @agronholm, thanks for the report!

I believe that's what I had to do in my project. IIRC STARTTLS isn't quite yet supported.

**Comment by agronholm** [comment]
This is what I did to make `STARTTLS` work:
```python3
class DummyController(Controller):
    def __init__(self, handler, factory=SMTP, hostname=None, port=0, *, ready_timeout=1.0,
                 enable_SMTPUTF8=True, ssl_context=None):
        super().__init__(handler, hostname=hostname, port=port, ready_timeout=ready_timeout,
                         enable_SMTPUTF8=enable_SMTPUTF8, ssl_context=None)
        self.__factory = factory
        self.__ssl_context = ssl_context

    def factory(self):
        return self.__factory(self.handler, enable_SMTPUTF8=self.enable_SMTPUTF8,
                              hostname=self.hostname, tls_context=self.__ssl_context)
```

**Comment by pepoluan** [comment]
Will the "pass-through" feature of 7289e6d8 suffice to solve this need?
