### ISSUE TITLE
production environment

### ISSUE THREAD

**Issue by giswangsj** [aio-libs/aiosmtpd#182]
Can I use it in production environment and receive mail from gmail?

**Comment by waynew** [comment]
That decision is entirely up to you(r stakeholders).

I'm vaguely aware of several places that use it, and I've been working on [my own mailserver](https://github.com/waynew/orouboros) that I use to power my personal email.

It does take a bunch of other setup - DNS, DKIM, SPF, if you want to have a reliable non-spammy server. But if you're just worried about *receiving* email, i.e. inbound only then there's no reason to *not* use aiosmtpd. You could probably use it as-is, without building any infrastructure on top of it.

**Comment by giswangsj** [comment]
Thanks for your reply. I can receive email from localhost on my pc. But on my mailserver, I can't receive email from gmail , is port=8025 ok? Should't it be 25 ?  How can I publish it ? I need your help. Thanks! PS: I can receive email from gmail by postfix , so I think the domain configration is ok , but I think aiosmtpd is more suitable for me

**Comment by waynew** [comment]
Sorry, that kind of question is out of scope for this project. You can find answers to your question on the Internet, and there are probably YouTube videos that will help you out, but there's probably nobody here who has the time to walk you through setting up a mailserver.

If you read the docs for aiosmtpd [you should be able to find how to change the port](https://aiosmtpd.readthedocs.io/en/stable/aiosmtpd/docs/cli.html).
