### ISSUE TITLE
aiosmtpd.smtp.SMTP(…) erroneously modifies ssl.SSLContext configuration

### ISSUE THREAD

**Issue by Dadeos** [aio-libs/aiosmtpd#191]
The initialisation of the `aiosmtpd.smtp.SMTP` class erroneously [modifies](https://github.com/aio-libs/aiosmtpd/blob/f3d04f9ae79cc72dbc68dbb1d8f638070c8033ec/aiosmtpd/smtp.py#L96-L100) the configuration of the [ssl.SSLContext](https://docs.python.org/3/library/ssl.html#ssl.SSLContext) passed to it as the `tls_context` parameter. The modifications made to the provided `ssl.SSLContext` are both unexpected and incorrect and therefore should be removed.

Setting the [ssl.SSLContext.check_hostname](https://docs.python.org/3/library/ssl.html#ssl.SSLContext.check_hostname) value to `False` is irrelevant because it is only applicable to _client-side_ sockets (i.e. [ssl.SSLSocket.server_side](https://docs.python.org/3/library/ssl.html#ssl.SSLSocket.server_side) is `False`) whereas the `aiosmtpd.smtp.SMTP` implementation manages _server-side_ sockets (i.e. [server_side=True](https://github.com/aio-libs/aiosmtpd/blob/f3d04f9ae79cc72dbc68dbb1d8f638070c8033ec/aiosmtpd/smtp.py#L409)).

Setting the [ssl.SSLContext.verify_mode](https://docs.python.org/3/library/ssl.html#ssl.SSLContext.verify_mode) to [ssl.CERT_NONE](https://docs.python.org/3/library/ssl.html#ssl.CERT_NONE) prohibits the use of TLS client certificates for client authentication (i.e. forcibly overwrites any previously configured value of [ssl.CERT_OPTIONAL](https://docs.python.org/3/library/ssl.html#ssl.CERT_OPTIONAL)) because:

> In server mode, no certificate is requested from the client, so the client does not send any for client cert authentication.

The comment regarding [RFC3207 part 4.1](https://tools.ietf.org/html/rfc3207#section-4.1) seems misguided, the RFC appears to suggest that the level of security/authenticity established via the TLS handshake, initiated by the issuing of the "STARTTLS" SMTP command, is a matter for the implementation; rather than that TLS client certificates should not be sought from clients by servers.

**Comment by pepoluan** [comment]
Good points.

I don't see any harm leaving the `check_hostname` line there, though. But maybe change `CERT_NONE` to `CERT_OPTIONAL`.

**Comment by Dadeos** [comment]
The perceived "harm" of these [lines](https://github.com/aio-libs/aiosmtpd/blob/f3d04f9ae79cc72dbc68dbb1d8f638070c8033ec/aiosmtpd/smtp.py#L96-L100) is that they are "unexpected and incorrect".

Functionally, leaving the [line](https://github.com/aio-libs/aiosmtpd/blob/f3d04f9ae79cc72dbc68dbb1d8f638070c8033ec/aiosmtpd/smtp.py#L99) that overrides the [ssl.SSLContext.check_hostname](https://docs.python.org/3/library/ssl.html#ssl.SSLContext.check_hostname) value is relatively harmless because it is unlikely that any user of the `aiosmtpd.smtp.SMTP` class would care about its value as it is irrelevant to _server-side_ sockets. I still advocate its removal however because the presence of redundant code is at best wasteful and at worst misleading.

I recommend against changing the [line](https://github.com/aio-libs/aiosmtpd/blob/f3d04f9ae79cc72dbc68dbb1d8f638070c8033ec/aiosmtpd/smtp.py#L100) that overrides the value of the [ssl.SSLContext.verify_mode](https://docs.python.org/3/library/ssl.html#ssl.SSLContext.verify_mode) from [ssl.CERT_NONE](https://docs.python.org/3/library/ssl.html#ssl.CERT_NONE) to [ssl.CERT_OPTIONAL](https://docs.python.org/3/library/ssl.html#ssl.CERT_OPTIONAL). To do so would alter the behaviour for existing uses of the `aiosmtpd.smtp.SMTP` class, I presume the vast majority of which either expect or are satisfied with the behaviour associated with a value of [ssl.CERT_NONE](https://docs.python.org/3/library/ssl.html#ssl.CERT_NONE). The _default_ value of  [ssl.SSLContext.verify_mode](https://docs.python.org/3/library/ssl.html#ssl.SSLContext.verify_mode) is [ssl.CERT_NONE](https://docs.python.org/3/library/ssl.html#ssl.CERT_NONE), both when created directly via  [ssl.SSLContext](https://docs.python.org/3/library/ssl.html#ssl.SSLContext) or via the [ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)](https://docs.python.org/3/library/ssl.html#ssl.create_default_context) creation method, making the  [line](https://github.com/aio-libs/aiosmtpd/blob/f3d04f9ae79cc72dbc68dbb1d8f638070c8033ec/aiosmtpd/smtp.py#L100) redundant in those cases.

For me, the issue is that the `aiosmtpd.smtp.SMTP` class takes an [ssl.SSLContext](https://docs.python.org/3/library/ssl.html#ssl.SSLContext), passed to it as the `tls_context` parameter, that represents a set of desired TLS/SSL configuration settings and then needlessly alters it. My current work-around for this behaviour is to avoid passing a value for the `tls_context` parameter and then simply setting the `aiosmtpd.smtp.SMTP.tls_context` value after the initialisation has been performed.

**Comment by pepoluan** [comment]
Must you put in so many links, links that you have provided in your original post? One link per 'thing' you want to highlight should be enough; we're not stupid children here. 😁

Back to more on-topic issue:

Changing `verify_mode` to `CERT_OPTIONAL` shouldn't impact clients. As the documentation explained, clients are free to send a certificate or to ignore the request for certificate. In fact, I've just tested on my local repo, and all tests -- including the ones testing STARTTLS -- pass. And there were no client-side certificate involved. Yes, the TLS handshake will be different, but if one treats TLS handshake as a blackbox, as is proper, there shouldn't be any surprises.

For me, setting the value to `CERT_OPTIONAL` _potentially_ increase security.

That said ...

> For me, the issue is that the aiosmtpd.smtp.SMTP class takes an ssl.SSLContext, passed to it as the tls_context parameter, that represents a set of desired TLS/SSL configuration settings and then needlessly alters it.

Ahh, now we're talking! 😄

If you put it that way, then I agree: `SMTP` class shouldn't edit the `tls_context` _at all_. Probably provide some warnings in the logs if the configuration is 'too weak', but that should be it; no editing what the user had provided. After all, we're all adult & responsible beings who should know a thing or two about proper SSL/TLS config 😉
