### ISSUE TITLE
Keep using nose2 or change to pytest?

### ISSUE THREAD

**Issue by pepoluan** [aio-libs/aiosmtpd#198]
As the title says.

I want to see what everyone thinks about this.

And I'll volunteer myself to do the heavy-lifting of rewriting all Test Cases into pytest if the community chooses too change.

**Comment by pkalemba** [comment]
if you need help  i would be pleased to help :)

**Comment by waynew** [comment]
Personally I'm a pytest fan

**Comment by warsaw** [comment]
Not that I have any say anymore, but I've converted my other projects to pytest.

**Comment by asvetlov** [comment]
Pytest is great

**Comment by pepoluan** [comment]
> Pytest is great (but the conversion takes some time)

Funnily enough, I have a branch in which I rewrote nearly the whole test suite implementing DRY principles... and now it looks almost like a pytest-based test suite 😅

**Comment by pepoluan** [comment]
I find it amusing that converting to pytest actually _increases_ the number of lines for the test cases. (Still on my own repo, though, haven't created a PR at all).

Maybe just not optimized enough, but at the moment I'm just aiming for a 1:1 test coverage. Optimization can come later...

@pkalemba I'll give you a nudge when my -- admittedly, a bit rough -- conversion has finished.

**Comment by pepoluan** [comment]
Just an update:

I hit a probable bug with pytest.

So I was converting `test_smtp.py` to pytest ... and accidentally wrote the wrong value in the `assert`, resulting in a test that fails ... and hangs. Correcting the value allows pytest to complete without issues.

But that got me thinking: If we made changes that caused a test to fail, the test shouldn't have hung; it should say "test failed" and ended gracefully.

If you are interested in hunting down the cause of this bug, here's my ticket on pytest's issue tracker:

https://github.com/pytest-dev/pytest/issues/7989

**Comment by pepoluan** [comment]
Okay I'm at a loss here...

Take a look at this minimal test case:

```python
import asyncio
import unittest

from aiosmtpd.controller import Controller
from aiosmtpd.handlers import Sink
from aiosmtpd.smtp import SMTP as Server
from smtplib import SMTP


def authenticator(mechanism, login, password):
    if login and login.decode() == 'goodlogin':
        return True
    else:
        return False


class DecodingController(Controller):
    def factory(self):
        return Server(self.handler, decode_data=True, enable_SMTPUTF8=True,
                      auth_require_tls=False, auth_callback=authenticator)


class TestSMTP(unittest.TestCase):
    def setUp(self):
        old_loop = asyncio.get_event_loop()
        new_loop = asyncio.new_event_loop()
        asyncio.set_event_loop(new_loop)
        controller = DecodingController(Sink, loop=new_loop)
        controller.start()

        def cleanup():
            print("###CLEANING UP###")
            controller.stop()
            new_loop.stop()
            asyncio.set_event_loop(old_loop)

        self.addCleanup(controller.stop)
        self.address = (controller.hostname, controller.port)

    def test_hanging(self):
        with SMTP(*self.address) as client:
            code, _ = client.helo("example.com")
            self.assertEqual(code, 250)
            assert code == 250
            print("###SENDING_MAIL###")
            code, _ = client.docmd("MAIL FROM: <alice@example.org>")
            self.assertEqual(code, 250)
            print("###SENDING_RCPT###")
            code, _ = client.docmd("RCPT TO: <bob@example.org>")
            self.assertEqual(code, 250)
            print("###SENDING_DATA###")
            code, _ = client.docmd("DATA")
            self.assertEqual(code, 250)  # We purposefully fail here
            client.close()
            print("###CLOSING_UP###")
```

Even running the above using **Unittest**, I'm getting stuck at the line marked `# We purposefully fail here`.

Removing that line -- or changing 250 to 354 in that line -- finishes successfuly. Both on Unittest and on Pytest.

I'm suspicious that the problem is in how Controller work ...

`Controller is sus`

**Comment by pepoluan** [comment]
After some thinking ... I'm seriously planning on taking out the `Controller` middleman.

After all, `test_smtp.py` is (mostly) testing the `aiosmtpd.smtp.SMTP` class, i.e., SMTP behavior over TCP.

We can -- and should! -- test `Controller` behavior separately.

Let me see what I can do...

**Comment by pepoluan** [comment]
**Update:** I barged through the hanging behavior by explicitly closing the controller for that one test case.

```python
    def test_data_abortconn(self, decoding_controller, client):
        controller = decoding_controller
        self._helo(client)
        resp = client.docmd("MAIL FROM: <alice@example.org>")
        assert resp == (250, b"OK")
        code, _ = client.docmd("RCPT TO: <bob@example.org>")
        assert resp == (250, b"OK")
        # Note: We NEED to manually stop the controller if we must abort while
        # in DATA phase. For reasons unclear, if we don't do that we'll hang
        # the test case should the assertion fail
        try:
            resp = client.docmd("DATA")
            assert resp == (354, b"End data with <CR><LF>.<CR><LF>")
        finally:
            controller.stop()
```

I will keep my eyes open for similar behavior in other test cases.

**Comment by pkalemba** [comment]
in my app created with aiosmtpd i created fixture which is yielding smtp client. As i understand your code you have a fixtrue "client" too. I cannot share my code, but here is a part:


`
@pytest.fixture()
def lmtp(request):
..
..
...
code, response = client.ehlo("example.com")
assert code == 250
assert response.split(b"\n")[0] == bytes(socket.getfqdn(), "utf-8")
yield client
client.quit()
controller.stop()

`

**Comment by pepoluan** [comment]
> As i understand your code you have a fixtrue "client" too.

Yup. The `client` fixture returns an SMTP client.

There are _lots_ of Controller & Handler combinations I have to separate the fixture for the SMTP client and the Controller+Handler.

In my snippet above, `decoding_controller` is defined as:

```python
@pytest.fixture
def decoding_controller(request) -> DecodingController:
    handler = _get_handler(request)
    controller = DecodingController(handler)
    controller.start()
    #
    yield controller
    #
    # Some test cases need to .stop() the controller inside themselves
    # in such cases, we must suppress Controller's raise of AssertionError
    # because Controller doesn't like .stop() to be invoked more than once
    with suppress(AssertionError):
        controller.stop()
```

While `_get_handler` is a helper function:

```python
def _get_handler(request, default=Sink):
    marker = request.node.get_closest_marker("handler_data")
    if marker:
        class_ = marker.kwargs.get("class_", Sink)
    else:
        class_ = Sink
    return class_()
```

`request` and `marker` is used like so:

```python
    @pytest.mark.handler_data(class_=ReceivingHandler)
    def test_bad_encodings(self, decoding_controller, client):
        handler: ReceivingHandler = decoding_controller.handler
        self._helo(client)
        mail_from = b"anne\xFF@example.com"
        mail_to = b"bart\xFF@example.com"
        self._ehlo(client, "test")
        client.send(b"MAIL FROM:" + mail_from + b"\r\n")
        assert client.getreply() == (250, b"OK")
        client.send(b"RCPT TO:" + mail_to + b"\r\n")
        assert client.getreply() == (250, b"OK")
        client.data("Test mail")
        assert len(handler.box) == 1
        envelope = handler.box[0]
        mail_from2 = envelope.mail_from.encode("utf-8", errors="surrogateescape")
        assert mail_from2 == mail_from
        mail_to2 = envelope.rcpt_tos[0].encode("utf-8", errors="surrogateescape")
        assert mail_to2 == mail_to
```

(I have no idea why [the original first did a HELO](https://github.com/aio-libs/aiosmtpd/blob/master/aiosmtpd/tests/test_smtp.py#L1411) then followed with an EHLO, though.)

**Comment by pepoluan** [comment]
Btw, I've finished converting `test_handlers.py`, `test_lmtp.py`, `test_main.py`, and `test_smtp.py` (the last one's a doozy...)

The work in progress (still at least a week away from PR-able) is here: https://github.com/pepoluan/aiosmtpd/tree/pytest_based

**Comment by P-EB** [comment]
> Not that I have any say anymore, but I've converted my other projects to pytest.

Your opinion still matters to a lot of people, because you have shown that your advice are still as good as ever. :)

**Comment by warsaw** [comment]
Aw, thanks PEB!

**Comment by pepoluan** [comment]
It had been a titanic effort, but I'm about 95-98% complete.

Would appreciate it if someone can glance at the code and provide some suggestions (if any) as I finish up the loose ends. (Which is why I'm still marking the PR as "draft")

**Comment by pepoluan** [comment]
### AND IT'S DONE.

Along the way:
- Rework tox strategy
- Total Upgrade of the Documentation
- (Possibly) Fixed the "Intermittent Coverage Failure" gremlin for good
- Implement GitHub Actions (though this one gets pushed directly to `master`, actually, and pulled back to my branch)
- And probably lots of other things that I no longer recall ...

A total of **112 commits** spanning 4'000+ lines ... gosh, it had been an adventure!

Code is ready for review. No major changes envisioned while it's undergoing review.

**Comment by pepoluan** [comment]
Seems like moving over to `pytest` will prevent issues such as #220 from happening... 🤨

(#220 is effectively a "wontfix", though. But the situation that led to that issue, we can prevent with migration to pytest.)

**Comment by pepoluan** [comment]
A bit of an update:

Due to my recent 10K* towards 1.2.3, there had been LOTS of new unit tests, meaning my `pytest-based` branch is now severely behind `master`.

It's _NOT_ being abandoned, though. I'll start updating it again as soon as we reach stability towards 1.2.3.

That said, for 1.2.3 I think I'll create a PR that changes the unit test runner from nose2 to pytest. I just tried it out on a whim, and it seems to work well.

I'll play around with it some more, before creating a PR proper.

**Comment by P-EB** [comment]
Thanks for this great work!
