### ISSUE TITLE
1.2.2 not released yet?

### ISSUE THREAD

**Issue by P-EB** [aio-libs/aiosmtpd#201]
Hi,

I was not able to find aiosmtpd 1.2.2 on PyPI, do you have a release schedule yet?

Thanks for your work!

**Comment by waynew** [comment]
Just built and uploaded 1.2.2!

**Comment by asvetlov** [comment]
This issue has been mentioned on **aio-libs**. There might be relevant details there:

https://aio-libs.discourse.group/t/aiosmtpd-1-2-2-released/155/1
