### ISSUE TITLE
Using GitHub Actions -- replace Travis CI integration?

### ISSUE THREAD

**Issue by pepoluan** [aio-libs/aiosmtpd#209]
I've created the YAML script to drive GitHub Actions (GA) testing, in commit c7630ae + 3b10324 (the latter because I didn't realize before that GA cancels everything in the matrix if any one of them fails.)

As you can [see here](https://github.com/aio-libs/aiosmtpd/actions), the tests passes for the current HEAD of `master`.

(You can manually trigger it to run by clicking on "aiosmtpd CI" on the left sidebar, then click "Run workflow".)

I don't know how to integrate them to the PR system, though. And/or how to replace Travis CI automatic testing of PR and pushes-to-PR.

**Comment by asvetlov** [comment]
I think the project will go to GitHub Actions sooner and later.
Sorry, I don't have the capacity to migrate the project myself but I can help with answering any GH Actions related question, sure.

**Comment by pepoluan** [comment]
Where does one configure PR checks to be done against GitHun Actions instead of Travis?

**Comment by pepoluan** [comment]
If I remove `.travis.yml`, will that also result in stopping the usage of Travis CI?

**Comment by pepoluan** [comment]
Done. Now I need that PR to be reviewed, and upon merging, Travis CI will stop and get replaced by GitHub Actions 😎
