### ISSUE TITLE
LGTM JavaScript error now causes check to fail instead of neutral?

### ISSUE THREAD

**Issue by pepoluan** [aio-libs/aiosmtpd#214]
As I prepared PR #213 , I noticed that now LGTM JavaScript failure causes the check to fail. IIRC previously this causes check to go "neutral" instead of fail.

I wonder if this is a recent change of settings, or because of me using `lgtm.yml` in the PR, or something else altogether...

That said,

Can we just disable JavaScript analysis for aiosmtpd? To the best of my knowledge, aiosmtpd does _not_ use JavaScript anywhere outside of documentation.

I have no "owner"/"admin" privilege so I cannot change LGTM.com's analysis settings for this project...

**Comment by asvetlov** [comment]
@webknjaz could you take a look?

**Comment by webknjaz** [comment]
It's not easy to do atm: https://discuss.lgtm.com/t/disable-javascript-analysis/2150.

**Comment by asvetlov** [comment]
We can disable the whole *lgtm* for `aiosmptd` easily if @pepoluan requests it.

I would note that the tool is useful (but not critical). I don't recall when `lgtm` reported about *the real* problem but it points on *untidiness* very well.

**Comment by pepoluan** [comment]
> 
> 
> We can disable the whole _lgtm_ for `aiosmptd` easily if @pepoluan requests it.
> 
> I would note that the tool is useful (but not critical). I don't recall when `lgtm` reported about _the real_ problem but it points on _untidiness_ very well.

I'm okay with lgtm for Python. It caught some questionable practices, so it's nice.

But lgtm for JavaScript seems to pick up on JS from ... somewhere (I've went up and down the clean repo tree and can't find any inkling of JS). And rather than telling where, it simply complains "all JavaScript files are empty or have syntax error."

It used to be no problem; JS analysis will result in a "neutral" score. For example #202:
> ![image](https://user-images.githubusercontent.com/642259/100546875-4213a900-3296-11eb-832d-957d382c0e53.png)

However newer PRs get a "fail" score. For example #213:
> ![image](https://user-images.githubusercontent.com/642259/100546905-75eece80-3296-11eb-82c9-bab64000e302.png)

Obviously I haven't touched any JS... since there aren't any 😅

I'm -0 on disabling LGTM for Python, +1 on disabling LGTM for JavaScript. And it it's too difficult and/or impossible to separately disable just the JavaScript portion, then I'm +1 on disabling LGTM completely.

### Alternatively...

We can also use CodeQL. It's [triggerable via Github Actions](https://github.com/github/codeql-action), and also much easier to configure.

**Comment by webknjaz** [comment]
I don't like that CodeQL doesn't have the same nice UI

**Comment by asvetlov** [comment]
Looking on the [doc](https://help.semmle.com/lgtm-enterprise/user/help/showing-hiding-query-results.html) I guess the simple config file can help:
```
queries:
  - exclude: javascript/*
```
Just put it in `lgtm.yml`

**Comment by pepoluan** [comment]
> Looking on the [doc](https://help.semmle.com/lgtm-enterprise/user/help/showing-hiding-query-results.html) I guess the simple config file can help:
> 
> ```
> queries:
>   - exclude: javascript/*
> ```
> 
> Just put it in `lgtm.yml`

Seems to be so. LGTM only obeys `lgtm.yml` files _already_ in `master` though. Since there is no such file at the moment, we might have to do an "emergency/urgent" commit directly against master.

**Comment by asvetlov** [comment]
Direct commit against master is ok if you use it in exceptional case.

**Comment by pepoluan** [comment]
> 
> 
> Direct commit against master is ok if you use it in exceptional case.

Cool then. Let me double check on what things one has to put in the lgtm.yml files, and I'll do a direct commit later.

**Comment by pepoluan** [comment]
Okay, I've done a direct commit. Added some tidbits I found on another repos.

Bad News: LGTM still run JavaScript analysis.

Good News: It now returns "neutral" scoring instead of "fail".

So although I'm still not 100% happy, I'll take what we can get.
