### ISSUE TITLE
Implement support for "AUTH LOGIN <username>"

### ISSUE THREAD

**Issue by pepoluan** [aio-libs/aiosmtpd#219]
Although the [documentation for AUTH LOGIN](https://www.ietf.org/archive/id/draft-murchison-sasl-login-00.txt) implies that `AUTH LOGIN` should not have args following it, Python's SMTP client implementation in `smtplib.SMTP` assumes so.

As a result, the strict process in current `master`'s AUTH LOGIN implementation will cause failure if `smtplib.SMTP` tries to auth using the LOGIN mechanism.

To explain visually:

This is how the transaction **_should_** be:

```
C: AUTH LOGIN
S: 334 VXNlciBOYW1lAA==
C: <base64-encoded username>
S: 334 UGFzc3dvcmQA
C: <base64-encoded password>
```

This is how `smtplib.SMTP` _wants_ it to be (when `initial_response_ok` is set to `True`, which is the default):

```
C: AUTH LOGIN <base-64-encoded username>
S: 334 UGFzc3dvcmQA
C: <base64-encoded password>
```

But, if `initial_response_ok=False` is used, then `smtplib.SMTP` will do it like this:

```
C: AUTH LOGIN
S: 334 VXNlciBOYW1lAA==
C: <base64-encoded password>  # yes, "password" not "username"
S: 334 UGFzc3dvcmQA
C: <base64-encoded password>
```

This is discussed in [**bpo-27820**](https://bugs.python.org/issue27820) (to which I've suggested a fix)

**Comment by pepoluan** [comment]
Really hope https://github.com/python/cpython/pull/24118 gets merged ...

Too late for 3.6 and 3.7, likely, but it had been a tech debt anyways and someone needs to rip off the band-aid...

**Comment by waynew** [comment]
FWIW: https://datatracker.ietf.org/doc/html/rfc4954#section-4 actually says that the client *can* provide an initial response
