### ISSUE TITLE
Colorizing with Rich? What do you think?

### ISSUE THREAD

**Issue by pepoluan** [aio-libs/aiosmtpd#221]
As the title asked.

[**Rich**](https://github.com/willmcgugan/rich) is a very nice library for colorification, not just for output (`print`) but also console logging, traceback, etc.

**Comment by waynew** [comment]
If it's an optional dependency I'd be fine with that - import rich in a try/catch and if it fails, fall back to some built-in functions that are no-ops. We can add extras_require to the setup so pip install is just as easy.

I'm just reluctant to add non-stdlib dependencies unless they're super useful/necessary.

**Comment by pepoluan** [comment]
After some thinking, it seems I was a bit ... un-sober when suggesting this. 😅 

I'll wontfix & close this.
