### ISSUE TITLE
1.2.4 is not available on PyPI

### ISSUE THREAD

**Issue by ddevault** [aio-libs/aiosmtpd#231]

**Comment by pepoluan** [comment]
Yes, it's not yet pushed to PyPI.

And in the meanwhilst I discovered that current version (1.2.3) is actually not fully compliant with RFC 4954, so I think we'll skip pushing to PyPI and push 1.2.4 instead.

**Comment by ddevault** [comment]
I can't certify the release on our end until it's on PyPI, FYI. Sounds good to skip it though if an issue was found.

**Comment by pepoluan** [comment]
Well then, since we agree to not release 1.2.3 (I've marked the "release" as "pre-release"), I think we can close this issue :-)

**Comment by ddevault** [comment]
Bump.

**Comment by pepoluan** [comment]
Release team is preparing for release to PyPI.

@waynew @warsaw

**Comment by pepoluan** [comment]
### [1.2.4 is now available on PyPI](https://pypi.org/project/aiosmtpd/1.2.4/)

**Comment by ddevault** [comment]
Thank you!

**Comment by pepoluan** [comment]
> 
> 
> Thank you!

1.3.0 will soon come out, though 😅 

Just 1 more PR to merge...
