### ISSUE TITLE
Docs are 404.

### ISSUE THREAD

**Issue by luckydonald** [aio-libs/aiosmtpd#240]
The documentation page https://aiosmtpd.readthedocs.io/en/latest/ is currently showing a not found error.
That page is liked by the official python documentation.

> ```text
>         \          SORRY            /
>          \                         /
>           \    This page does     /
>            ]   not exist yet.    [    ,'|
>            ]                     [   /  |
>            ]___               ___[ ,'   |
>            ]  ]\             /[  [ |:   |
>            ]  ] \           / [  [ |:   |
>            ]  ]  ]         [  [  [ |:   |
>            ]  ]  ]__     __[  [  [ |:   |
>            ]  ]  ] ]\ _ /[ [  [  [ |:   |
>            ]  ]  ] ] (#) [ [  [  [ :===='
>            ]  ]  ]_].nHn.[_[  [  [
>            ]  ]  ]  HHHHH. [  [  [
>            ]  ] /   `HH("N  \ [  [
>            ]__]/     HHH  "  \[__[
>            ]         NNN         [
>            ]         N/"         [
>            ]         N H         [
>           /          N            \
>          /           q,            \
>         /                           \
> ```
> _Fig. 1: "screenshot"_     
  
     
Additionally this git is not linked in the pip module page, so I had to dive into an archive.org [version from 2019](http://web.archive.org/web/20190103085755/https://aiosmtpd.readthedocs.io/en/latest/).

**Comment by pepoluan** [comment]
Stable works, though: https://aiosmtpd.readthedocs.io/en/stable/

And going directly to the subdirs work for latest: https://aiosmtpd.readthedocs.io/en/latest/aiosmtpd/docs/intro.html

It seems that I have to reinstate symlink to index.

Will do an urgent push.

**Comment by luckydonald** [comment]
For reference https://docs.python.org/3/library/smtpd.html links there.

**Comment by pepoluan** [comment]
> 
> 
> For reference https://docs.python.org/3/library/smtpd.html links there.

Yes, I'm well aware of that. This is why this issue gets "urgent" fixing status.

Still trying to figure out how to tell Sphinx to output the HTML files on the right spot, but in the meanwhilst, I've put in an index.html that's supposed to redirect to where the docs live.

https://aiosmtpd.readthedocs.io/ and https://aiosmtpd.readthedocs.io/en/latest/ are now no longer 404.

**Comment by pepoluan** [comment]
Closing the issue for now.

**Comment by luckydonald** [comment]
👍 

Could you think about adding the GitHub to the pip package page?

**Comment by pepoluan** [comment]
> 
> 
> 👍
> 
> Could you think about adding the GitHub and other critical links to the pip package page?

It will be part of 1.3

![image](https://user-images.githubusercontent.com/642259/106359370-ff795600-6344-11eb-94ad-3580a383ae40.png)
