### ISSUE TITLE
No way to limit concurrent inbound SMTP connections?!?

### ISSUE THREAD

**Issue by davidmcnabnz** [aio-libs/aiosmtpd#282]
Hi there,

I have a use-case where I need to set a limit to the number of concurrent inbound SMTP connections. The behaviour I need is that if any additional connections come in, they get closed instantly.

Are you able to advise the best way to accomplish this within aiosmtpd?

Cheers
David

**Comment by waynew** [comment]
I think this might be best achieved with a proxy? It's possible that you could do it with the underlying sockets, but I'm not sure. It's definitely a backwards requirement from what everyone else needs 🤣
