### ISSUE TITLE
QA: Workflow should run on newer versions of Python and macOS

### ISSUE THREAD

**Issue by nikochiko** [aio-libs/aiosmtpd#306]
https://github.com/aio-libs/aiosmtpd/blob/215b854447e2567bbc5e3665d9a648d7b1fa2c82/.github/workflows/unit-testing-and-coverage.yml#L92

The testing versions are outdated. 3.6 has reached end-of-life, 3.10 should be tested for, and 3.11 is coming out in a couple of weeks. QA should be updated accordingly. (https://devguide.python.org/versions/)

macOS 10.15 is also outdated, tests should be run on 11.7 or 12.6 (https://endoflife.date/macos)

ubuntu 22.04 can be included too (https://endoflife.date/ubuntu)

**Comment by pepoluan** [comment]
Closed by PR #324
