### ISSUE TITLE
Python 3.11 compatible release

### ISSUE THREAD

**Issue by CharlemagneLasse** [aio-libs/aiosmtpd#322]
It seems like various distributions will loose mailman 3 because they switched to python 3.10 or 3.11 - and the last release of aiosmtpd doesn't have support for these python versions. See #309 and #314

For example, Debian will have its first freeze in January 2023: https://release.debian.org/bookworm/freeze_policy.html
It would be nice when there is a new release (after newly 2 years) which is compatible with the current Python versions.

**Comment by CharlemagneLasse** [comment]
@pepoluan, the Debian bug about aiosmtpd removal can be found at https://bugs.debian.org/1025019

**Comment by pepoluan** [comment]
Okay, that's serious.

What is the root cause of the test failures?

**Comment by CharlemagneLasse** [comment]
> What is the root cause of the test failures?

Afaik, that Debian packages the latest released version. And the latest released version doesn't include the fixes from #309 + #314.

**Comment by pepoluan** [comment]
Hmmm.... so basically we better package the latest as, say, 1.5.0 and ask the Debian maintainers to just go forward with 1.5.0?

**Comment by CharlemagneLasse** [comment]
That would be my hope. But of course, I can only make suggestions. You know the project and its state - but I thought it is fair to make this suggestion because Debian is not the only distribution facing such problems - and users of pypi also seem to be unable to use aiosmtpd with the current Python version (due to the age of the last release)

**Comment by pepoluan** [comment]
I have just fixed GitHub CI. All tests run green now. I am 90% confident of packaging into 1.4.3.

**Comment by P-EB** [comment]
Thanks for the work. I'm happy to package in Debian either 1.4.3 or 1.5.0 if you manage to finish it by mid-january. :)

Anyway, I'll take the first release you shoot.

**Comment by pepoluan** [comment]
> Thanks for the work. I'm happy to package in Debian either 1.4.3 or 1.5.0 if you manage to finish it by mid-january. :)
> 
> Anyway, I'll take the first release you shoot.

Well, for 1.4.3 I think this month can be released. The changes are minor anyways.

1.5.0 has many new ideas and will represent quite a heavy lifting, so it might not be able to make it even in mid-January 😅 

I'm currently running the GitHub CI tests again to ensure that things are still green, then gonna update NEWS.rest ... and then figure out how I used to release the packages 😆

**Comment by pepoluan** [comment]
Version 1.4.3rc1 released.

If this one goes well, within the next week I'll re-release as 1.4.3 without any changes (except reversioning)

**Comment by pepoluan** [comment]
@CharlemagneLasse can you grab 1.4.3rc2 and do some tests?

I want to release 1.4.3 final a.s.a.p. to allow other teams depending on us some time to do their own testing.

**Comment by CharlemagneLasse** [comment]
Sorry, I was traveling (on purpose) without internet-connected devices and thus missed your message. But it looks good.

Thanks for your assistance.
