### ISSUE TITLE
Can you guys add SPF(Sender Policy Framework) auth function/argument to this framework?

### ISSUE THREAD

**Issue by yingshaoxo** [aio-libs/aiosmtpd#371]
Here is an example:

https://github.com/sdgathman/pyspf#:~:text=The%20RFC%204408/7208%20compliant%20API

___

Without the auth, we can't really be sure who send an email, which could be dangerous.

___

And how can I get the source IP info of an email from `aiosmtpd`?

**Comment by yingshaoxo** [comment]
All I need is to make sure if an email was sent from an IP that was owned by a domain the email claimed to be.

In another words, if it is a forged email, we directly drop it without processing.

I even think that you guys could make it an argument like: `drop_fake_source_email=True`

**Comment by magnus-een** [comment]
Hi @yingshaoxo ,

You can get the connecting IP address from the Sessions [peer](https://aiosmtpd.readthedocs.io/en/latest/concepts.html#Session.peer) value.
Once you have this, you can use any existing python SPF library ([pyspf ](https://pypi.org/project/pyspf/)for example) to validate the SPF result.

Best,
Magnus

**Comment by yingshaoxo** [comment]
OK, thank you
