### ISSUE TITLE
Send 550 in response to SMTP RCPT

### ISSUE THREAD

**Issue by Mortal** [aio-libs/aiosmtpd#47]
"Real" SMTP servers often reply with 550 in response to the RCPT command, so that the SMTP client doesn't have to send message data for a recipient that doesn't exist on the server. Would it be possible to add a hook in aiosmtpd.smtp.SMTP.smtp_DATA to validate incoming recipients immediately instead of just adding them blindly to envelope.rcpt_tos?

I've been running an [SMTP mailing list forwarder based on smtpd](https://github.com/TK-IT/mail) for two years and am looking into porting that to aiosmtpd when 1.0 is released.

**Comment by warsaw** [comment]
I think this will be handled with #41 

The idea is that the handler would determine whether the recipient is valid or not (via the `handler.handle_RCPT` hook).  Some of the details of that PR still need to be worked out, e.g. the method names need to be updated, but do take a look and see if the general approach will let you do what you need to do.

We will definitely get 1.0 out in the next couple of weeks.  I am presenting aiosmtpd at Pycon 2017, so it better be ready by then. :)

**Comment by Mortal** [comment]
I hadn't noticed PR #41. As far as I can see, the patch doesn't do what I want: SMTP.smtp_RCPT still unconditionally responds 250 OK. I would like event_handler.rcpt to be able to reject the recipient with either a 4xx transient error or 5xx permanent error (most of the time, 550 no such user).

Should we continue the discussion here or in #41?

I'm looking forward to the last-minute 1.0 release on May 21. :-)

**Comment by warsaw** [comment]
@Mortal I think you've identified a good point.  `rcpt` (to be called `handle_RCPT`) should not return an address object, but instead it should return a code, or otherwise cause a code to percolate up to `smtp_RCPT()`.

Yes, let's continue the discussion over in #41 -  and I sure hope to get 1.0 out way before then! :)

**Comment by Mortal** [comment]
Implemented in #55.
