### ISSUE TITLE
Duplicated HELO/EHLO

### ISSUE THREAD

**Issue by Varbin** [aio-libs/aiosmtpd#78]
As already mentioned in source code (https://github.com/aio-libs/aiosmtpd/blob/c25b878473b086150d32fcd21c35c58099947e5f/aiosmtpd/smtp.py#L264, also in original smtpd's code) a second HELO/EHLO is rejected but the standart says it should be handled as a RSET command.

Is there any special reason to not allow duplicated HELO/EHLO?  I think the best way is to do the same other SMTP servers do: Allowing a duplicated HELO/EHLO.
Another option is to have a configuration option.

**Comment by warsaw** [comment]
Do you mean specifically [RFC 5321, $4.1.4](https://tools.ietf.org/html/rfc5321#section-4.1.4)?  I would agree that to be compliant with this section, we should treat a second `HELO`/`EHLO` as semantically equivalent to a `RSET` followed by the `HELO`/`EHLO`.

**Comment by Varbin** [comment]
Yes I do mean RFC 5321, $4.1.4.

**Comment by warsaw** [comment]
@Varbin Thanks for the response.  I'd like to fix this, but as we're up against the Pycon deadline, I'm going to milestone this to post 1.0.

**Comment by Varbin** [comment]
I fully understand that. Also the duplicated `HELO` / `EHLO` should probably never be a problem - which SMTP client sends two `HELO` / `EHLO` commands in one session?

**Comment by warsaw** [comment]
@Varbin I wouldn't expect it from a non-buggy client.

**Comment by zvyn** [comment]
There is a patch for the stdlib implementation at http://bugs.python.org/issue21783, I might find some time to port it over later today.

In terms of relevance: Using HELO or EHLO to reset a session is permitted by the standard so I think we should support it.

I don't know about clients but I did use this when debugging SMTP servers manually before (test something, see what response you get, type EHLO and try something different). In that case it seems better to EHLO instead of RSET to explicitly start a new SMTP session while keeping the TCP connection.

**Comment by Varbin** [comment]
A patch would be:

```diff
--- smtp.py.old	2017-05-07 15:53:22 +0000
+++ smtp.py	2017-05-07 15:54:13 +0000
@@ -261,10 +261,6 @@
         if not hostname:
             yield from self.push('501 Syntax: HELO hostname')
             return
-        # See issue #21783 for a discussion of this behavior.
-        if self.session.host_name:
-            yield from self.push('503 Duplicate HELO/EHLO')
-            return
         self._set_rset_state()
         self.session.extended_smtp = False
         status = yield from self._call_handler_hook('HELO', hostname)
@@ -278,11 +274,6 @@
         if not hostname:
             yield from self.push('501 Syntax: EHLO hostname')
             return
-        # See https://bugs.python.org/issue21783 for a discussion of this
-        # behavior.
-        if self.session.host_name:
-            yield from self.push('503 Duplicate HELO/EHLO')
-            return
         self._set_rset_state()
         self.session.extended_smtp = True
         yield from self.push('250-%s' % self.hostname)

```
